// ============================================================
// FILE: generate_stream.cpp
// PURPOSE:
// Build deterministic universal byte stream
// ============================================================

#include <iostream>
#include <vector>
#include <fstream>
#include <filesystem>
#include <opencv2/opencv.hpp>
#include "logger.h"

namespace fs = std::filesystem;

std::vector<uint8_t> universal_stream;

void process_image(const std::string& path) {

    cv::Mat img = cv::imread(path);

    if (img.empty()) {
        std::cout << "Failed: " << path << "\n";
        return;
    }

    for (int y = 0; y < img.rows; y++) {

        for (int x = 0; x < img.cols; x++) {

            cv::Vec3b p = img.at<cv::Vec3b>(y, x);

            universal_stream.push_back(p[0]);
            universal_stream.push_back(p[1]);
            universal_stream.push_back(p[2]);
        }
    }

    // boundary separator
    for (int i = 0; i < 64; i++) {
        universal_stream.push_back(255);
    }

    std::cout << "Processed: " << path << "\n";
}

void save_stream() {

    std::ofstream out(
        "STREAM/stream.bin",
        std::ios::binary
    );

    out.write(
        (char*)universal_stream.data(),
        universal_stream.size()
    );

    out.close();
}

int main() {

    fs::create_directory("STREAM");

    BenchmarkTimer timer;

    timer.tic();

    for (auto& p : fs::directory_iterator("IMG")) {
        process_image(p.path().string());
    }

    save_stream();

    double elapsed = timer.toc();

    uint64_t stream_size =
        file_size_bytes("STREAM/stream.bin");

    std::cout
        << "\n========== STREAM GENERATION ==========\n";

    print_stat(
        "Generated Byte Count",
        universal_stream.size()
    );

    print_stat(
        "Stream Size",
        mb(stream_size),
        "MB"
    );

    print_stat(
        "Generation Time",
        elapsed,
        "sec"
    );

    append_log(
        "========== STREAM GENERATION =========="
    );

    append_log(
        "Byte Count: " +
        std::to_string(universal_stream.size())
    );

    append_log(
        "Stream Size MB: " +
        std::to_string(mb(stream_size))
    );

    append_log(
        "Generation Time Sec: " +
        std::to_string(elapsed)
    );

    append_log("");

    return 0;
}   