// ============================================================
// FILE: generate_stream.cpp
// ============================================================

#include <iostream>
#include <vector>
#include <fstream>
#include <filesystem>
#include <opencv2/opencv.hpp>

#include "logger.h"
#include "config.h"

namespace fs = std::filesystem;

std::vector<uint8_t> universal_stream;

void process_image(
    const std::string& path
) {

    cv::Mat img = cv::imread(path);

    if (img.empty()) {

        std::cout
            << "Failed: "
            << path
            << "\n";

        return;
    }

    for (int y = 0; y < img.rows; y++) {

        for (int x = 0; x < img.cols; x++) {

            cv::Vec3b p =
                img.at<cv::Vec3b>(y, x);

            // exact pixels
            universal_stream.push_back(p[0]);
            universal_stream.push_back(p[1]);
            universal_stream.push_back(p[2]);

            // optional generated variants
            if (ENABLE_GENERATIVE_MODE) {

                for (int i = 1;
                     i <= GENERATIVE_REPEAT_COUNT;
                     i++) {

                    uint8_t b2 =
                        std::min(255,
                        p[0] + i);

                    uint8_t g2 =
                        std::min(255,
                        p[1] + i);

                    uint8_t r2 =
                        std::min(255,
                        p[2] + i);

                    universal_stream.push_back(b2);
                    universal_stream.push_back(g2);
                    universal_stream.push_back(r2);
                }
            }
        }
    }

    // image boundary separator
    for (int i = 0;
         i < STREAM_SEPARATOR_SIZE;
         i++) {

        universal_stream.push_back(255);
    }

    std::cout
        << "Processed: "
        << path
        << "\n";
}

void save_stream() {

    std::ofstream out(
        "STREAM/stream.bin",
        std::ios::binary
    );

    out.write(
        (char*)universal_stream.data(),
        universal_stream.size()
    );

    out.close();
}

int main() {

    int ATTEMPT =
        get_attempt_number();

    fs::create_directory("STREAM");

    BenchmarkTimer timer;

    timer.tic();

    for (
        auto& p :
        fs::directory_iterator("IMG")
    ) {

        process_image(
            p.path().string()
        );
    }

    save_stream();

    double elapsed =
        timer.toc();

    uint64_t stream_size =
        file_size_bytes(
            "STREAM/stream.bin"
        );

    std::cout
        << "\n========== STREAM GENERATION ==========\n";

    print_stat(
        "Attempt Number",
        std::to_string(ATTEMPT)
    );

    print_stat(
        "Generation Mode",
        ENABLE_GENERATIVE_MODE
        ? "GENERATIVE"
        : "EXACT"
    );

    print_stat(
        "Generated Byte Count",
        human_size(
            universal_stream.size()
        )
    );

    print_stat(
        "Stream Size",
        human_size(stream_size)
    );

    print_stat(
        "Generation Time",
        elapsed,
        "sec"
    );

    append_log(
        "========================================"
    );

    append_log(
        "ATTEMPT #" +
        std::to_string(ATTEMPT)
    );

    append_log(
        "========== STREAM GENERATION =========="
    );

    append_log(
        "Generation Mode: " +
        std::string(
            ENABLE_GENERATIVE_MODE
            ? "GENERATIVE"
            : "EXACT"
        )
    );

    append_log(
        "Generated Byte Count: " +
        human_size(
            universal_stream.size()
        )
    );

    append_log(
        "Stream Size: " +
        human_size(stream_size)
    );

    append_log(
        "Generation Time: " +
        std::to_string(elapsed) +
        " sec"
    );

    append_log("");

    return 0;
}