#!/usr/bin/env python3
import re
import sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

LOG_PATTERNS = {
    'generation_mode': re.compile(r'Generation Mode:\s*(\w+)'),
    'generated_byte_count_mb': re.compile(r'Generated Byte Count:\s*([\d\.]+)\s*MB'),
    'stream_size_mb': re.compile(r'Stream Size(?: MB)?:\s*([\d\.]+)\s*MB'),
    'generation_time_sec': re.compile(r'Generation Time(?: Sec)?:\s*([\d\.]+)\s*(?:sec)?'),
    'match_found_yes': re.compile(r'Match Found:\s*(YES|NO)'),
    'no_match_found': re.compile(r'NO MATCH FOUND'),
    'matching_time_sec': re.compile(r'Matching Time(?: Sec)?:\s*([\d\.]+)\s*(?:sec)?'),
    'compression_ratio': re.compile(r'Compression Ratio:\s*([\d\.]+)'),
    'transfer_compression': re.compile(r'Transfer Compression:\s*([\d\.]+)'),
    'system_compression': re.compile(r'System Compression:\s*([\d\.]+)'),
    'original_mb': re.compile(r'Original MB:\s*([\d\.]+)'),
    'image': re.compile(r'Image:\s*(.+)'),
    'coord_mb': re.compile(r'Coord MB:\s*([\d\.]+)'),
    'map_mb': re.compile(r'Map MB:\s*([\d\.]+)'),
    'reconstruction_time_sec': re.compile(r'Reconstruction Time(?: Sec)?:\s*([\d\.]+)\s*(?:sec)?'),
    'reconstructed_mb': re.compile(r'Reconstructed MB:\s*([\d\.]+)'),
    'verification': re.compile(r'Verification:\s*(.*)'),
    'matched_length': re.compile(r'Matched Length:\s*([0-9]+)'),
    'byte_count': re.compile(r'Byte Count:\s*([0-9]+)'),
    'tile_count': re.compile(r'Tile Count:\s*([0-9]+)'),
}


def parse_attempt_block(lines):
    text = '\n'.join(lines)
    d = {}
    for key, pat in LOG_PATTERNS.items():
        m = pat.search(text)
        if m:
            d[key] = m.group(1) if m.groups() else True
    # normalize numeric fields
    for k in ['generated_byte_count_mb','stream_size_mb','generation_time_sec','matching_time_sec','compression_ratio','transfer_compression','system_compression','original_mb','coord_mb','map_mb','reconstruction_time_sec','reconstructed_mb']:
        if k in d:
            try:
                d[k] = float(d[k])
            except Exception:
                d[k] = None
    for k in ['matched_length','byte_count','tile_count']:
        if k in d:
            try:
                d[k] = int(d[k])
            except Exception:
                d[k] = None
    if 'match_found_yes' in d:
        d['match_found'] = True if d.get('match_found_yes','NO')=='YES' else False
        d.pop('match_found_yes', None)
    elif 'no_match_found' in d:
        d['match_found'] = False
        d.pop('no_match_found', None)
    else:
        # leave as None
        d['match_found'] = None
    return d


def main():
    if len(sys.argv) < 2:
        print('Usage: generate_plots.py /path/to/benchmark.log')
        sys.exit(1)
    p = Path(sys.argv[1])
    if not p.exists():
        print('File not found:', p)
        sys.exit(1)
    text = p.read_text()
    lines = text.splitlines()

    attempts = []
    cur_attempt = None
    cur_lines = []
    for i, line in enumerate(lines):
        m = re.match(r"^ATTEMPT #\s*(\d+)", line)
        if m:
            if cur_attempt is not None:
                # finalize previous
                parsed = parse_attempt_block(cur_lines)
                parsed['attempt'] = cur_attempt
                attempts.append(parsed)
            cur_attempt = int(m.group(1))
            cur_lines = []
            continue
        if cur_attempt is not None:
            cur_lines.append(line)
    # finalize last
    if cur_attempt is not None:
        parsed = parse_attempt_block(cur_lines)
        parsed['attempt'] = cur_attempt
        attempts.append(parsed)

    # If no ATTEMPT sections found, try to parse other occurrences of stream generation blocks
    if not attempts:
        # fallback: look for blocks that start with "========== STREAM GENERATION ==========" and gather following 8 lines
        blocks = []
        for i, line in enumerate(lines):
            if 'STREAM GENERATION' in line:
                block = lines[i:i+20]
                parsed = parse_attempt_block(block)
                parsed['attempt'] = len(blocks)+1
                blocks.append(parsed)
        attempts = blocks

    if not attempts:
        print('No attempts or stream blocks found in', p)
        sys.exit(1)

    df = pd.DataFrame(attempts)
    df = df.sort_values('attempt')

    outdir = Path('outputs')
    outdir.mkdir(exist_ok=True)
    csv_path = outdir / 'benchmark_parsed.csv'
    md_path = outdir / 'benchmark_table.md'
    png_path = outdir / 'benchmark_plot.png'

    df.to_csv(csv_path, index=False)

    # write markdown table
    try:
        md = df.fillna('').to_markdown(index=False)
    except Exception:
        # fallback simple markdown
        md = '| ' + ' | '.join(df.columns) + ' |\n'
        md += '| ' + ' | '.join(['---']*len(df.columns)) + ' |\n'
        for _, row in df.iterrows():
            md += '| ' + ' | '.join([str(row[c]) if pd.notna(row[c]) else '' for c in df.columns]) + ' |\n'
    md_path.write_text(md)

    # plotting - produce clearer line and bar charts for all available metrics
    def safe_col(name):
        return name in df.columns and df[name].notna().any()

    # Sizes: line chart
    fig1, ax1 = plt.subplots(figsize=(10, 4))
    if safe_col('stream_size_mb'):
        ax1.plot(df['attempt'], df['stream_size_mb'], marker='o', label='Stream Size (MB)')
    if safe_col('generated_byte_count_mb'):
        ax1.plot(df['attempt'], df['generated_byte_count_mb'], marker='x', label='Generated Byte Count (MB)')
    ax1.set_xlabel('Attempt')
    ax1.set_ylabel('Size (MB)')
    ax1.set_title('Stream / Generated Sizes')
    ax1.legend()
    fig1.tight_layout()
    sizes_png = outdir / 'benchmark_sizes.png'
    fig1.savefig(sizes_png)

    # Times: grouped bar chart for generation and matching, plus reconstruction time as line
    fig2, ax2 = plt.subplots(figsize=(10, 4))
    width = 0.35
    x = df['attempt']
    offsets = x - width/2
    has_gen = safe_col('generation_time_sec')
    has_match = safe_col('matching_time_sec')
    if has_gen:
        ax2.bar(x - width/4, df['generation_time_sec'], width=width/2, label='Generation Time (s)')
    if has_match:
        ax2.bar(x + width/4, df['matching_time_sec'], width=width/2, label='Matching Time (s)')
    if safe_col('reconstruction_time_sec'):
        ax2.plot(df['attempt'], df['reconstruction_time_sec'], color='tab:red', marker='o', label='Reconstruction Time (s)')
    ax2.set_xlabel('Attempt')
    ax2.set_ylabel('Time (s)')
    ax2.set_title('Timings')
    ax2.legend()
    fig2.tight_layout()
    times_png = outdir / 'benchmark_times.png'
    fig2.savefig(times_png)

    # Compression: bar chart (log scale if values vary widely)
    fig3, ax3 = plt.subplots(figsize=(10, 4))
    if safe_col('compression_ratio'):
        vals = df['compression_ratio'].fillna(0)
        ax3.bar(df['attempt'], vals, color='tab:green')
        ax3.set_ylabel('Compression Ratio')
        ax3.set_xlabel('Attempt')
        ax3.set_title('Compression Ratio per Attempt')
        # if range is large, use log scale for visibility
        if vals.max() / max(vals.min() if vals.min() > 0 else vals.max(), 1) > 100:
            ax3.set_yscale('log')
    elif safe_col('transfer_compression'):
        vals = df['transfer_compression'].fillna(0)
        ax3.bar(df['attempt'], vals, color='tab:green')
        ax3.set_ylabel('Transfer Compression')
        ax3.set_xlabel('Attempt')
        ax3.set_title('Transfer Compression per Attempt')
        if vals.max() / max(vals.min() if vals.min() > 0 else vals.max(), 1) > 100:
            ax3.set_yscale('log')
    else:
        ax3.text(0.5, 0.5, 'No compression metrics found', ha='center')
    fig3.tight_layout()
    comp_png = outdir / 'benchmark_compression.png'
    fig3.savefig(comp_png)

    # Combined detailed figure: sizes, counts/lengths, compression, and timings
    fig, axes = plt.subplots(4, 1, figsize=(12, 16))

    # Sizes and reconstruction
    ax = axes[0]
    if safe_col('original_mb'):
        ax.plot(df['attempt'], df['original_mb'], marker='o', label='Original MB')
    if safe_col('stream_size_mb'):
        ax.plot(df['attempt'], df['stream_size_mb'], marker='x', label='Stream Size MB')
    if safe_col('generated_byte_count_mb'):
        ax.plot(df['attempt'], df['generated_byte_count_mb'], marker='^', label='Generated Byte Count MB')
    if safe_col('reconstructed_mb'):
        ax.plot(df['attempt'], df['reconstructed_mb'], marker='s', label='Reconstructed MB')
    ax.set_ylabel('MB')
    ax.set_title('Sizes')
    ax.legend()

    # Counts and matched length
    ax = axes[1]
    plotted = False
    if safe_col('byte_count'):
        ax.bar(df['attempt'] - 0.2, df['byte_count'] / 1e6, width=0.4, label='Byte Count (MB)')
        plotted = True
    if safe_col('tile_count'):
        ax.bar(df['attempt'] + 0.2, df['tile_count'] / 1e3, width=0.4, label='Tile Count (k)')
        plotted = True
    if safe_col('matched_length'):
        ax.plot(df['attempt'], df['matched_length'] / 1e6, color='tab:red', marker='o', label='Matched Length (M)')
        plotted = True
    if not plotted:
        ax.text(0.5, 0.5, 'No count/length metrics found', ha='center')
    ax.set_ylabel('Count (scaled)')
    ax.set_title('Counts & Matched Length')
    ax.legend()

    # Compression metrics
    ax = axes[2]
    if safe_col('compression_ratio'):
        ax.plot(df['attempt'], df['compression_ratio'], marker='o', label='Compression Ratio')
    if safe_col('transfer_compression'):
        ax.plot(df['attempt'], df['transfer_compression'], marker='x', label='Transfer Compression')
    if safe_col('system_compression'):
        ax.plot(df['attempt'], df['system_compression'], marker='s', label='System Compression')
    ax.set_ylabel('Compression')
    ax.set_title('Compression Metrics')
    try:
        vals = pd.concat([df[c].dropna() for c in ['compression_ratio','transfer_compression','system_compression'] if c in df.columns])
        if not vals.empty and vals.max() / max(vals.min() if vals.min() > 0 else vals.max(), 1) > 100:
            ax.set_yscale('log')
    except Exception:
        pass
    ax.legend()

    # Timings
    ax = axes[3]
    if safe_col('generation_time_sec'):
        ax.bar(df['attempt'] - 0.2, df['generation_time_sec'], width=0.4, label='Generation Time (s)')
    if safe_col('matching_time_sec'):
        ax.bar(df['attempt'] + 0.2, df['matching_time_sec'], width=0.4, label='Matching Time (s)')
    if safe_col('reconstruction_time_sec'):
        ax.plot(df['attempt'], df['reconstruction_time_sec'], color='tab:red', marker='o', label='Reconstruction Time (s)')
    ax.set_ylabel('Seconds')
    ax.set_xlabel('Attempt')
    ax.set_title('Timings')
    ax.legend()

    # annotate image names where available
    if 'image' in df.columns:
        for i, row in df.iterrows():
            if pd.notna(row.get('image')):
                try:
                    y = row.get('stream_size_mb', None)
                    if y is None or pd.isna(y):
                        y = row.get('original_mb', None)
                    if y is None or pd.isna(y):
                        continue
                    axes[0].annotate(str(row['image']), (row['attempt'], y), xytext=(5, 5), textcoords='offset points', fontsize=8)
                except Exception:
                    pass

    fig.tight_layout()
    fig.savefig(png_path)
    print('Wrote detailed combined plot to', png_path)
    print('Wrote sizes plot to', sizes_png)
    print('Wrote times plot to', times_png)
    print('Wrote compression plot to', comp_png)

    # Scaled unified plot: rescale each numeric series to the same peak so small values are visible
    numeric_cols = [
        'original_mb','stream_size_mb','generated_byte_count_mb','reconstructed_mb',
        'byte_count','tile_count','matched_length',
        'compression_ratio','transfer_compression','system_compression',
        'generation_time_sec','matching_time_sec','reconstruction_time_sec'
    ]
    present_cols = [c for c in numeric_cols if c in df.columns and df[c].notna().any()]
    if present_cols:
        # compute per-column maxima
        maxes = {c: float(df[c].abs().max()) for c in present_cols}
        global_max = max(maxes.values()) if maxes else 1.0
        scaled = {}
        scales = {}
        for c in present_cols:
            cmax = maxes.get(c, 0.0)
            if cmax <= 0:
                factor = 1.0
            else:
                factor = global_max / cmax
            scales[c] = factor
            scaled[c] = df[c] * factor
        # plot scaled series
        figs, ax = plt.subplots(figsize=(12, 6))
        color_cycle = plt.rcParams['axes.prop_cycle'].by_key()['color']
        for i, c in enumerate(present_cols):
            color = color_cycle[i % len(color_cycle)]
            ax.plot(df['attempt'], scaled[c], marker='o', label=f"{c} (scaled x{scales[c]:.2g})", color=color)
        ax.set_title('Unified scaled view (each series scaled to same peak)')
        ax.set_xlabel('Attempt')
        ax.set_ylabel('Scaled value (all series peak aligned)')
        ax.grid(True, linestyle='--', alpha=0.4)
        ax.legend(ncol=2, fontsize='small')
        scaled_png = outdir / 'benchmark_scaled.png'
        figs.tight_layout()
        figs.savefig(scaled_png)
        print('Wrote scaled unified plot to', scaled_png)

    # Unit-grouped plot: each subplot uses a natural unit scale
    mb_cols = [
        ('original_mb', 'Original MB'),
        ('stream_size_mb', 'Stream Size MB'),
        ('generated_byte_count_mb', 'Generated Byte Count MB'),
        ('reconstructed_mb', 'Reconstructed MB'),
        ('map_mb', 'Map MB'),
        ('coord_mb', 'Coord MB'),
    ]
    sec_cols = [
        ('generation_time_sec', 'Generation Time (s)'),
        ('matching_time_sec', 'Matching Time (s)'),
        ('reconstruction_time_sec', 'Reconstruction Time (s)'),
    ]
    count_cols = [
        ('byte_count', 'Byte Count (M)'),
        ('tile_count', 'Tile Count (k)'),
        ('matched_length', 'Matched Length (M)'),
    ]
    comp_cols = [
        ('compression_ratio', 'Compression Ratio'),
        ('transfer_compression', 'Transfer Compression'),
        ('system_compression', 'System Compression'),
    ]

    groups = [
        ('MB metrics', mb_cols, 'MB'),
        ('Second metrics', sec_cols, 'Seconds'),
        ('Count metrics', count_cols, 'Count (scaled)'),
        ('Compression metrics', comp_cols, 'Compression'),
    ]
    group_fig, group_axes = plt.subplots(len(groups), 1, figsize=(12, 18), sharex=True)
    for ax, (title, cols, ylabel) in zip(group_axes, groups):
        plotted = False
        for col, label in cols:
            if safe_col(col):
                if col == 'byte_count':
                    ax.plot(df['attempt'], df[col] / 1e6, marker='o', label=label)
                elif col == 'tile_count':
                    ax.plot(df['attempt'], df[col] / 1e3, marker='s', label=label)
                elif col == 'matched_length':
                    ax.plot(df['attempt'], df[col] / 1e6, marker='d', label=label)
                else:
                    ax.plot(df['attempt'], df[col], marker='o', label=label)
                plotted = True
        if not plotted:
            ax.text(0.5, 0.5, f'No {title.lower()} found', ha='center', va='center')
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(loc='upper left', fontsize='small')
        ax.grid(True, linestyle='--', alpha=0.4)
    group_axes[-1].set_xlabel('Attempt')
    group_fig.tight_layout()
    unit_plot = outdir / 'benchmark_unit_grouped.png'
    group_fig.savefig(unit_plot)
    print('Wrote unit-grouped plot to', unit_plot)

    print('Wrote CSV to', csv_path)
    print('Wrote markdown table to', md_path)
    print('Wrote plot to', png_path)


if __name__ == '__main__':
    main()
